/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as CellsRouteImport } from './routes/cells'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as SeedsRouteImport } from './routes/seeds'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const CellsRoute = CellsRouteImport.update({
  id: '/cells',
  path: '/cells',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsRoute = SeedsRouteImport.update({
  id: '/seeds',
  path: '/seeds',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRoute
  '/cells': typeof CellsRoute
  '/findings': typeof FindingsRoute
  '/ledger': typeof LedgerRoute
  '/providers': typeof ProvidersRoute
  '/seeds': typeof SeedsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRoute
  '/cells': typeof CellsRoute
  '/findings': typeof FindingsRoute
  '/ledger': typeof LedgerRoute
  '/providers': typeof ProvidersRoute
  '/seeds': typeof SeedsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRoute
  '/cells': typeof CellsRoute
  '/findings': typeof FindingsRoute
  '/ledger': typeof LedgerRoute
  '/providers': typeof ProvidersRoute
  '/seeds': typeof SeedsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaign'
    | '/cells'
    | '/findings'
    | '/ledger'
    | '/providers'
    | '/seeds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaign'
    | '/cells'
    | '/findings'
    | '/ledger'
    | '/providers'
    | '/seeds'
  id:
    | '__root__'
    | '/'
    | '/campaign'
    | '/cells'
    | '/findings'
    | '/ledger'
    | '/providers'
    | '/seeds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignRoute: typeof CampaignRoute
  CellsRoute: typeof CellsRoute
  FindingsRoute: typeof FindingsRoute
  LedgerRoute: typeof LedgerRoute
  ProvidersRoute: typeof ProvidersRoute
  SeedsRoute: typeof SeedsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cells': {
      id: '/cells'
      path: '/cells'
      fullPath: '/cells'
      preLoaderRoute: typeof CellsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds': {
      id: '/seeds'
      path: '/seeds'
      fullPath: '/seeds'
      preLoaderRoute: typeof SeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignRoute: CampaignRoute,
  CellsRoute: CellsRoute,
  FindingsRoute: FindingsRoute,
  LedgerRoute: LedgerRoute,
  ProvidersRoute: ProvidersRoute,
  SeedsRoute: SeedsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
